#.travis.yml

language: node_js
node_js:
  - "10"
dist: trusty
sudo: false

branches:
  only:
    - master

cache:
  directories:
    - node_modules

before_script:
  - npm install -g @angular/cli
  - npm install --save terser@3.16.1

script:
  - ng lint
  # - npm run test:ci
  - ng build --prod --base-href https://dlevkov.github.io/op-stackoverflow-viewer/
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $git_token
  local_dir: dist/op-stackoverflow-viewer

notifications:
  email:
    on_failure: change
    on_success: change
